Repository AY1920S1-CS2103T-F14-4/main, pull requests merged in 2019-11, with the labels that each got.

#208 Added savepdf Command.
  build.gradle
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/SavePdfCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SavePdfCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/pdfmanager/PdfCoverPageLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfCreator.java
  src/main/java/seedu/address/model/pdfmanager/PdfCustomerLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfDriverLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfPageHeaderLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfSampleLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfTableHeaderLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfTaskLayout.java
  src/main/java/seedu/address/model/pdfmanager/PdfWrapperLayout.java
  src/main/java/seedu/address/model/pdfmanager/exceptions/PdfNoTaskToDisplayException.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/exceptions/TaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: pr.ToBeReviewd

#210 Fix bugs. Removed unused commands from UG. Added refresh function for list.
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteIdCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/pdfmanager/PdfTaskLayout.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: pr.ToBeReviewd

#218 added badges for code quality and coverage
  README.adoc
Labels: pr.ToBeReviewd

#219 Enhance assign workflow
  docs/diagrams/AssignActivityDiagram.puml
  docs/images/AssignActivityDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/optimizer/Candidate.java
  src/main/java/seedu/address/logic/optimizer/ScheduleOptimizer.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SuggestCommandParser.java
  src/main/java/seedu/address/model/person/Driver.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/person/SchedulingSuggestion.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/testutil/SampleEntity.java
Labels: pr.ToBeReviewd

#223 Bugfix for Notification window Issue #222 and #206
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/ui/NotificationWindow.java
Labels: pr.ToBeReviewd, priority.High

#234 Added Driver Rating System #52 View customer and driver window #241
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddDriverCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/ViewCustomerWindowCommand.java
  src/main/java/seedu/address/logic/commands/ViewDriverWindowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCustomerWindowCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewDriverWindowCommandParser.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/Driver.java
  src/main/java/seedu/address/model/person/DriverRating.java
  src/main/java/seedu/address/model/person/exceptions/RatingException.java
  src/main/java/seedu/address/storage/JsonAdaptedDriver.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/CustomerWindow.java
  src/main/java/seedu/address/ui/DriverCard.java
  src/main/java/seedu/address/ui/DriverWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Map.java
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/CustomerWindow.fxml
  src/main/resources/view/DriverListCard.fxml
  src/main/resources/view/DriverWindow.fxml
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/testutil/SampleEntity.java
Labels: pr.ToBeReviewd, priority.Medium

#239 Added update command to update Company information and added savepdf for delivery order.
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/SavePdfCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SavePdfCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/DriverManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/GstRegistrationNumber.java
  src/main/java/seedu/address/model/company/RegistrationNumber.java
  src/main/java/seedu/address/model/pdfmanager/PdfCreator.java
  src/main/java/seedu/address/model/pdfmanager/PdfManager.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfCanvasLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfCompanyCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfCompanySignatureCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfConditionsCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfCustomerCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfCustomerSignatureLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfDeliveryNumberCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfDeliveryOrder.java
  src/main/java/seedu/address/model/pdfmanager/pdfdeliveryorder/PdfTaskDescriptionCanvas.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfCoverPageLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfCustomerLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfDriverLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfPageHeaderLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfSampleLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfTableHeaderLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfTaskLayout.java
  src/main/java/seedu/address/model/pdfmanager/pdftasksummary/PdfWrapperLayout.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CentralManager.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonSerializableCentralManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SavePdfCommandTest.java
  src/test/java/seedu/address/testutil/SampleEntity.java
Labels: pr.ToBeReviewd

#245 Fix editC/editD command not updating task information. Change "AddressBookParser" to "CommandParser"
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditDriverCommand.java
  src/main/java/seedu/address/logic/parser/CommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueEntityList.java
  src/test/java/seedu/address/logic/parser/CommandParserTest.java
Labels: priority.High

#243 Fix duration parser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#246 History and statistic
  docs/UserGuide.adoc
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/GoCommand.java
  src/main/java/seedu/address/logic/commands/ViewDriverTaskCommand.java
  src/main/java/seedu/address/logic/parser/GoCommandParser.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Goods.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandCard.java
  src/main/java/seedu/address/ui/CommandListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotificationWindow.java
  src/main/java/seedu/address/ui/StatisticPanel.java
  src/main/resources/view/CommandCard.fxml
  src/main/resources/view/CommandListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: pr.ToBeReviewd

#244 Update UG/DG
  DeleteSequenceDiagram.png
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ViewCustomerWindowSequenceDiagram.puml
  docs/diagrams/ViewDriverWindowSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ViewCustomerWindowSequenceDiagram.png
  docs/images/ViewDriverWindowSequenceDiagram.png
  docs/team/samyj2606.adoc
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/testutil/CustomerBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
Labels: pr.ToBeReviewd

#236 Update UG, DG and portfolio page
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AssignActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/AssignActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/Ui.png
  docs/images/user-guide/adding-task.png
  docs/images/user-guide/reschedule-task.png
  docs/images/user-guide/suggest-task.png
  docs/stylesheets/asciidoctor.css
  docs/stylesheets/gh-pages.css
  docs/team/tysng.adoc
Labels: pr.ToBeReviewd
