Repository AY1920S1-CS2103T-F14-4/main, pull requests merged in 2019-10, with the labels that each got.

#64 Updated "Getting Started" in User guide.
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: priority.Low

#67 Edit User Stories table (Last 3 rows)
  docs/DeveloperGuide.adoc
Labels: priority.High

#65 Updated "About Us".
  docs/AboutUs.adoc
  docs/images/junnbang.png
Labels: priority.High

#68 Updated developerguide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: priority.High

#69 Fixed "AboutUs" image relative path.
  docs/AboutUs.adoc
Labels: priority.High

#73 Added user stories
  docs/DeveloperGuide.adoc
  docs/images/cheeyou.png
Labels: priority.High

#75 Resolve Picture not showing
  docs/images/argvampir.png
Labels: priority.High

#81 Adds `Task`, `TaskList`, `TaskManager` classes
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/main/java/seedu/address/model/task/execeptions/TaskException.java
  src/main/java/seedu/address/model/task/execeptions/TaskNotFoundException.java
Labels: priority.High

#79 Add IDE config to pass stylecheck
  ProjectIDESettings.xml
Labels: priority.High

#78 add Goods and Description
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/Description.java
  src/main/java/seedu/address/model/Goods.java
Labels: ToBeReview, priority.High

#92 Support finding first avaiable time slot
  src/main/java/seedu/address/model/EventTime.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/test/java/seedu/address/model/DurationTest.java
  src/test/java/seedu/address/model/EventTimeTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
Labels: pr.ToBeReviewd

#100 Edit task command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteIdCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Description.java
  src/main/java/seedu/address/model/DriverManager.java
  src/main/java/seedu/address/model/EventTime.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/CustomerList.java
  src/main/java/seedu/address/model/person/CustomerManager.java
  src/main/java/seedu/address/model/person/Driver.java
  src/main/java/seedu/address/model/person/DriverList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/model/task/TaskStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: pr.ToBeReviewd

#101 Add assign command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/legacy/AddressBook.java
  src/main/java/seedu/address/model/legacy/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/legacy/UniquePersonList.java
  src/main/java/seedu/address/model/person/Driver.java
  src/main/java/seedu/address/model/person/Schedule.java
Labels: pr.ToBeReviewd, priority.High

#106 Add free command
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteIdCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FreeCommandParser.java
  src/main/java/seedu/address/model/person/Driver.java
Labels: pr.ToBeReviewd

#107 Update UG and DG.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTaskCommand.puml
  docs/diagrams/CentralManager.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/Task.puml
  docs/images/AddTaskCommand.png
  docs/images/CentralManager.png
  docs/images/StorageClassDiagram.png
  docs/images/Task.png
Labels: pr.ToBeReviewd, priority.High

#108 Update Assign command UG/DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AssignActivityDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/images/AssignActivityDiagram.png
  docs/images/CommitActivityDiagram.png
Labels: pr.ToBeReviewd

#112 Update UG&DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddCustomerCommand.puml
  docs/diagrams/AddDriverCommand.puml
  docs/diagrams/Customer.puml
  docs/diagrams/Driver.puml
  docs/images/AddCustomerCommand.png
  docs/images/AddDriverCommand.png
  docs/images/Customer.png
  docs/images/Driver.png
Labels: pr.ToBeReviewd, priority.High

#118 Centralized Storage for all managers.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddDriverCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteIdCommand.java
  src/main/java/seedu/address/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddDriverCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/model/CustomerManager.java
  src/main/java/seedu/address/model/DriverManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/id/IdManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/CentralManager.java
  src/main/java/seedu/address/storage/CentralManagerStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedId.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonCentralManagerStorage.java
  src/main/java/seedu/address/storage/JsonSerializableCentralManager.java
  src/main/java/seedu/address/storage/JsonSerializableCustomerManager.java
  src/main/java/seedu/address/storage/JsonSerializableTaskManager.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: pr.ToBeReviewd, priority.High

#120 Added Read Command
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/ReadIdCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteIdCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ReadIdCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
Labels: pr.ToBeReviewd, priority.High

#124 update UG / DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTaskCommand.puml
  docs/diagrams/ModelInteractWithManagers.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AddTaskCommand.png
  docs/images/ModelInteractWithManagers.png
  docs/images/StorageClassDiagram.png
Labels: pr.ToBeReviewd, priority.High

#125 Added automated testing for tasks and tasklist.
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FreeCommand.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/SampleEntity.java
Labels: pr.ToBeReviewd, priority.High

#137 Added List and Clear Command. Fixed bugs mentioned in issues.
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/id/IdManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskManager.java
  src/main/java/seedu/address/storage/JsonAdaptedId.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: pr.ToBeReviewd, priority.High

#141 Fix #127: suggested time is no longer in the past
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/GlobalClock.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/model/DriverManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Driver.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
  src/test/java/seedu/address/testutil/SampleEntity.java
Labels: pr.ToBeReviewd
